"""Change product and transaction

Revision ID: 366fb8bf1696
Revises: ebe025529dde
Create Date: 2023-03-26 23:12:12.649382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366fb8bf1696'
down_revision = 'ebe025529dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
