"""Change product and transaction

Revision ID: 58a4d783c2ba
Revises: 366fb8bf1696
Create Date: 2023-03-26 23:13:42.017835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a4d783c2ba'
down_revision = '366fb8bf1696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
