"""Change client

Revision ID: 5c68d47036b2
Revises: 576d647b6aac
Create Date: 2023-03-26 23:00:48.688969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c68d47036b2'
down_revision = '576d647b6aac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
