"""Change product and transaction

Revision ID: 8ce9385bfb08
Revises: 58a4d783c2ba
Create Date: 2023-03-26 23:18:18.525375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce9385bfb08'
down_revision = '58a4d783c2ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
