"""Change product and transaction

Revision ID: dfa3472c8610
Revises: 5c68d47036b2
Create Date: 2023-03-26 23:08:11.774772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa3472c8610'
down_revision = '5c68d47036b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
