"""Change product and transaction

Revision ID: ebe025529dde
Revises: dfa3472c8610
Create Date: 2023-03-26 23:09:19.778224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe025529dde'
down_revision = 'dfa3472c8610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
